[project]
name = "trail-dawg"
version = "0.1.0"
readme = "README.md"
requires-python = [">=3.13,<3.14"]
dependencies = [
    "nicegui>=2.20.0",
    "ruff>=0.12.2",
]

[tool.ruff]
target-version = "py313"
line-length = 180

